# Generated by Django 5.2.4 on 2025-09-21 08:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_indexes", "0002_alter_blogindex_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindex",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("code", 6),
                    ("quote", 7),
                    ("paragraph", 8),
                    ("video", 9),
                    ("image", 10),
                    ("document", 11),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide which programming language is used",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide copy buttons",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide window buttons",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Untitled",
                            "help_text": "File name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Auto"),
                                ("bash", "Bash"),
                                ("c", "C"),
                                ("cpp", "C++"),
                                ("csharp", "C#"),
                                ("css", "CSS"),
                                ("dart", "Dart"),
                                ("dockerfile", "Dockerfile"),
                                ("go", "Go"),
                                ("html", "HTML"),
                                ("java", "Java"),
                                ("javascript", "JavaScript"),
                                ("json", "JSON"),
                                ("kotlin", "Kotlin"),
                                ("lua", "Lua"),
                                ("markdown", "Markdown"),
                                ("php", "PHP"),
                                ("python", "Python"),
                                ("ruby", "Ruby"),
                                ("rust", "Rust"),
                                ("scss", "SCSS"),
                                ("shell", "Shell"),
                                ("sql", "SQL"),
                                ("swift", "Swift"),
                                ("typescript", "TypeScript"),
                                ("xml", "XML"),
                                ("yaml", "YAML"),
                                ("plaintext", "Plain text"),
                            ],
                            "help_text": "Programming language",
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Code content", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("show_language", 0),
                                ("show_copy_btn", 1),
                                ("show_window_btns", 2),
                                ("file_name", 3),
                                ("language", 4),
                                ("code", 5),
                            ]
                        ],
                        {"help_text": "Code"},
                    ),
                    7: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    8: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    9: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    10: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Image"},
                    ),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Page content",
                verbose_name="content",
            ),
        ),
    ]
