# Generated by Django 5.2.4 on 2025-09-26 08:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_indexes", "0003_alter_blogindex_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindex",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 3),
                    ("document", 4),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Page content",
                verbose_name="content",
            ),
        ),
    ]
