# Generated by Django 5.2.6 on 2025-10-04 06:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_articles", "0007_alter_blogarticle_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 6),
                    ("document", 7),
                    ("code", 14),
                    ("accordion", 23),
                    ("alert", 35),
                    ("carousel", 41),
                    ("diff", 44),
                    ("fab", 49),
                    ("hover_gallery", 52),
                    ("list", 61),
                    ("tabs", 74),
                    ("steps", 80),
                    ("timeline", 88),
                    ("toast", 91),
                    ("browser", 95),
                    ("code_mockup", 96),
                    ("phone", 99),
                    ("window", 101),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image attribution",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4), ("attribution", 5)]],
                        {"help_text": "Image"},
                    ),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide which programming language is used",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide copy buttons",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide window buttons",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Untitled",
                            "help_text": "File name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Auto"),
                                ("bash", "Bash"),
                                ("c", "C"),
                                ("cpp", "C++"),
                                ("csharp", "C#"),
                                ("css", "CSS"),
                                ("dart", "Dart"),
                                ("dockerfile", "Dockerfile"),
                                ("go", "Go"),
                                ("html", "HTML"),
                                ("java", "Java"),
                                ("javascript", "JavaScript"),
                                ("json", "JSON"),
                                ("kotlin", "Kotlin"),
                                ("lua", "Lua"),
                                ("markdown", "Markdown"),
                                ("php", "PHP"),
                                ("python", "Python"),
                                ("ruby", "Ruby"),
                                ("rust", "Rust"),
                                ("scss", "SCSS"),
                                ("shell", "Shell"),
                                ("sql", "SQL"),
                                ("swift", "Swift"),
                                ("typescript", "TypeScript"),
                                ("xml", "XML"),
                                ("yaml", "YAML"),
                                ("plaintext", "Plain text"),
                            ],
                            "help_text": "Programming language",
                        },
                    ),
                    13: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Code content", "required": True},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("show_language", 8),
                                ("show_copy_btn", 9),
                                ("show_window_btns", 10),
                                ("file_name", 11),
                                ("language", 12),
                                ("code", 13),
                            ]
                        ],
                        {"help_text": "Code"},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accordion name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                            "help_text": "Accordion style",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "check-circle2",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Wether to show or hide item content",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item title", "max_length": 64, "required": True},
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Item content", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 17),
                                ("is_expanded", 18),
                                ("title", 19),
                                ("content", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"help_text": "Accordion items", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 15), ("style", 16), ("items", 22)]],
                        {"help_text": "Accordion"},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "alert-triangle",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if alert is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("soft", "Soft"),
                                ("outline", "Outline"),
                                ("dash", "Dash"),
                            ],
                            "help_text": "Alert style",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Alert level",
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "code",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "help_text": "Alert message",
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Action label",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Action internal link", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Action external link", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("success", "Success"),
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Action button color",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 17),
                                ("label", 29),
                                ("page", 30),
                                ("url", 31),
                                ("color", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (33,),
                        {"help_text": "Alert actions", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 24),
                                ("is_vertical", 25),
                                ("style", 26),
                                ("level", 27),
                                ("message", 28),
                                ("actions", 34),
                            ]
                        ],
                        {"help_text": "Alert"},
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if carousel is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Caption", "max_length": 128, "required": False},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("video", 37), ("caption", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.ListBlock",
                        (39,),
                        {"help_text": "Carousel items", "required": True},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 36), ("items", 40)]],
                        {"help_text": "Carousel"},
                    ),
                    42: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 1"},
                    ),
                    43: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 2"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("item_1", 42), ("item_2", 43)]],
                        {"help_text": "Diff"},
                    ),
                    45: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if FAB is vertical or flower shaped (quarter circle)",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 17),
                                ("label", 29),
                                ("page", 30),
                                ("url", 31),
                                ("color", 32),
                            ]
                        ],
                        {"help_text": "FAB toggle btn", "required": True},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 17),
                                ("label", 29),
                                ("page", 30),
                                ("url", 31),
                                ("color", 32),
                            ]
                        ],
                        {"help_text": "FAB main action", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (33,),
                        {"help_text": "FAB items", "required": True},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("is_flower", 45),
                                ("toggle", 46),
                                ("main", 47),
                                ("items", 48),
                            ]
                        ],
                        {"help_text": "FAB"},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 38)]],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (50,),
                        {"help_text": "Gallery items", "required": True},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 51)]],
                        {"help_text": "Hover gallery"},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "List title", "max_length": 64, "required": True},
                    ),
                    54: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Item image"},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Item description",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Item internal link", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Item external link", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.ListBlock",
                        (33,),
                        {"help_text": "Actions", "required": False},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 54),
                                ("title", 19),
                                ("description", 55),
                                ("page", 56),
                                ("url", 57),
                                ("actions", 58),
                            ]
                        ],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {"help_text": "List items", "required": True},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 53), ("items", 60)]],
                        {"help_text": "List"},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tab name", "max_length": 64, "required": True},
                    ),
                    63: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if tab buttons position is reversed",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("border", "Border"),
                                ("box", "Box"),
                                ("lift", "Lift"),
                            ],
                            "help_text": "Tab style",
                        },
                    ),
                    65: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if tab is selected",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 24),
                                ("is_vertical", 25),
                                ("style", 26),
                                ("level", 27),
                                ("message", 28),
                                ("actions", 34),
                            ]
                        ],
                        {"help_text": "Alert", "required": True},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("show_language", 8),
                                ("show_copy_btn", 9),
                                ("show_window_btns", 10),
                                ("file_name", 11),
                                ("language", 12),
                                ("code", 13),
                            ]
                        ],
                        {"help_text": "Code", "required": True},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4), ("attribution", 5)]],
                        {"help_text": "Image", "required": True},
                    ),
                    69: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": True},
                    ),
                    70: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich text", "required": True},
                    ),
                    71: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("alert", 66),
                                ("code", 67),
                                ("image", 68),
                                ("video", 69),
                                ("text", 70),
                            ]
                        ],
                        {"help_text": "Tab Content", "required": True},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("is_selected", 65), ("content", 71)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.ListBlock",
                        (72,),
                        {"help_text": "Tab items", "required": True},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 62),
                                ("is_reversed", 63),
                                ("style", 64),
                                ("items", 73),
                            ]
                        ],
                        {"help_text": "Tabs"},
                    ),
                    75: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if Steps is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item name", "max_length": 64, "required": True},
                    ),
                    77: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                                ("success", "Success"),
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Item color",
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 76), ("icon", 17), ("color", 77)]],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {"help_text": "Steps items", "required": True},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 75), ("items", 79)]],
                        {"help_text": "Steps"},
                    ),
                    81: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if timeline is compact",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if timeline is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if dates should snap to icons",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Item date", "required": True},
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Item content",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("date", 84), ("icon", 17), ("content", 85)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.ListBlock",
                        (86,),
                        {"help_text": "Timeline items", "required": True},
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("is_compact", 81),
                                ("is_vertical", 82),
                                ("snap_to_icon", 83),
                                ("items", 87),
                            ]
                        ],
                        {"help_text": "Timeline"},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 24),
                                ("is_vertical", 25),
                                ("style", 26),
                                ("level", 27),
                                ("message", 28),
                                ("actions", 34),
                            ]
                        ],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.ListBlock",
                        (89,),
                        {"help_text": "Toast items", "required": True},
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 90)]],
                        {"help_text": "Toast"},
                    ),
                    92: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide toolbar",
                            "required": False,
                        },
                    ),
                    93: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Browser URL", "required": True},
                    ),
                    94: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Browser wallpaper"},
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("show_url", 92), ("url", 93), ("wallpaper", 94)]],
                        {"help_text": "Browser mockup"},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 12), ("code", 13)]],
                        {"help_text": "Code mockup"},
                    ),
                    97: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide camera",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Phone wallpaper"},
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("show_camera", 97), ("wallpaper", 98)]],
                        {"help_text": "Phone mockup"},
                    ),
                    100: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Window wallpaper"},
                    ),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("wallpaper", 100)]],
                        {"help_text": "Window mockup"},
                    ),
                },
                help_text="Article content",
                verbose_name="content",
            ),
        ),
    ]
